# Here we can overwrite default values from default.yml and/or we can add extra values
# then the 'config' package will merge both default and env specific values
db:
  host: 'localhost'
  username: 'postgres'
  password: '111111'
  synchronize: true

jwt:
  secret: 'TopSecretTaskManagement'
